# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
#  - template: build/job.yml  # Template reference
#    parameters:
#      name: windows
#      pool:
#        vmImage: 'windows-latest'
#  - template: build/job.yml  # Template reference
#    parameters:
#      name: linux
#      pool:
#        vmImage: 'ubuntu-latest'

  - job: linux
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    
    - checkout: self
      fetchDepth: 0


    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: Determine Version
      inputs:
        useConfigFile: true
        configFilePath: 'gitversion.yml'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls -R'
  
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jasase/solaredgetoinfluxdb'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/src'
        tags: |
          $(GitVersion.NuGetVersionV2)
          latest
          
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jasase/solaredgetoinfluxdb'
        command: 'push'
        tags: |
          $(GitVersion.NuGetVersionV2)
          latest
  